version: 2

project_name: proj

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: proj
    main: ./cmd/proj
    binary: proj
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

  - id: proj-tmux
    main: ./plugins/proj-tmux
    binary: proj-tmux
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  # Archive for proj (all platforms including Windows)
  - id: proj
    builds:
      - proj
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

  # Archive for proj-tmux (linux/darwin only, no Windows)
  - id: proj-tmux
    builds:
      - proj-tmux
    formats:
      - tar.gz
    name_template: >-
      proj-tmux_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^style:'
      - '^refactor:'
      - Merge pull request
      - Merge branch

nfpms:
  - id: proj
    package_name: proj
    builds:
      - proj
      - proj-tmux
    vendor: gfanton
    homepage: https://github.com/gfanton/project
    maintainer: gfanton <gfanton@example.com>
    description: A Git-based project management tool with zoxide-like navigation
    license: MIT
    formats:
      - deb
      - rpm
    dependencies:
      - git
    recommends:
      - zsh
      - tmux

# Generate Nix package (uncomment repository section if you have a NUR repo)
nix:
  - name: proj
    # repository:
    #   owner: gfanton
    #   name: nur-packages
    description: A Git-based project management tool with zoxide-like navigation
    homepage: https://github.com/gfanton/project
    license: mit
    extra_install: |-
      installShellCompletion --cmd proj \
        --bash <($out/bin/proj completion bash) \
        --fish <($out/bin/proj completion fish) \
        --zsh <($out/bin/proj completion zsh)

release:
  prerelease: auto
  mode: replace
