name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

  build:
    matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: make lint
      - run: make build
      - run: make test
