name: relase
on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: make build
      - uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          hooks: goreleaser
          changelog-generator-opt: "emojis=true"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
